const github='https://github.com/GilbertoMonroy67';
const projects=[
['Heros Hunter','Aplicación web','Ayuda a descubrir y explorar héroes rápidamente.',['HTML','CSS','JavaScript'],'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/HerosHunter-EVZMRqmP0XUIJhrTNIAHpMqWHxrDDD.png'],
['Login MVC + Docker','Aplicación web','Centraliza el acceso de usuarios con arquitectura MVC y SQL.',['C#','.NET','ASP.NET'],'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Proyecto%20Login%20MVC%20Docker-htWrdZfrxNCIU9pihfo0FE96CU4XNU.png'],
['Yard Sale','Frontend e-commerce','Catálogo responsive inspirado en un marketplace.',['HTML','CSS','JavaScript'],'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/YardSale-UpcXUYU1F6HMU9L06djwdMbBwwlh2t.png'],
['Task Manager','Productividad','Organiza tareas pendientes desde una interfaz mínima.',['JavaScript','HTML','CSS'],'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ToDoJavaScript-c0dSwELSiKz3DyZOD2So6RiUkLKeBF.png'],
['ChatBot','Lógica conversacional','Respuestas rápidas para acciones frecuentes.',['C#','.NET'],'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ChatBot-fwradfuqLlz5zWKCLaIiSf1Qhbjzy0.png'],
['Calculadora de ecuaciones','Consola C#','Resuelve ecuaciones y sistemas con un flujo guiado.',['C#','.NET'],'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Calculadora-tgMmvm9TCwbSnLggBY6nr52gOLPwqp.png']];
const techs=[['C#','Lógica de negocio','https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/csharp/csharp-original.svg'],['.NET','Desarrollo backend','https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/dot-net/dot-net-original.svg'],['ASP.NET','Aplicaciones web MVC','https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/dot-net/dot-net-original.svg'],['SQL','Persistencia y consultas','https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/mysql/mysql-original.svg'],['Git','Control de versiones','https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/git/git-original.svg'],['JavaScript','Interactividad web','https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/javascript/javascript-original.svg']];
const certificates=['Buenas prácticas y código limpio en C#','Programación con C#','Pensamiento lógico','Algoritmos y diagramas de flujo','Datos, estructuras y funciones','Estructuras de control','Lenguajes de programación','Bases de datos con SQL','Fundamentos de bases de datos','Ingeniería de software','JavaScript básico','Frontend Developer','JavaScript práctico','React.js','Webpack','Terminal y línea de comandos','Inteligencia Artificial','Ciberseguridad'];
let index=0;const track=document.querySelector('#project-track');
function renderProjects(){track.innerHTML=projects.map((p,i)=>`<article class="project-card"><img src="${p[4]}" alt="Captura de ${p[0]}"><div class="project-card-body"><span class="project-tag">${p[1]}</span><h3>${p[0]}</h3><p>${p[2]}</p><div class="techs">${p[3].map(t=>`<span>${t}</span>`).join('')}</div><a class="project-link" href="${github}" target="_blank" rel="noreferrer">Ver repositorio →</a></div></article>`).join('');document.querySelector('#counter').textContent=`${index+1} / ${projects.length}`;}
function move(step){index=(index+step+projects.length)%projects.length;renderProjects();track.scrollTo({left:track.children[index].offsetLeft,behavior:'smooth'});}document.querySelector('#prev').onclick=()=>move(-1);document.querySelector('#next').onclick=()=>move(1);renderProjects();setInterval(()=>move(1),5000);
document.querySelector('#tech-grid').innerHTML=techs.map(t=>`<article class="tech-card"><img src="${t[2]}" alt=""><div><h3>${t[0]}</h3><p>${t[1]}</p></div></article>`).join('');document.querySelector('#cert-grid').innerHTML=certificates.map((c,i)=>`<article class="cert-card"><span>${String(i+1).padStart(2,'0')}</span><h3>${c}</h3><small>Certificación completada</small></article>`).join('');
